### ISSUE TITLE
How does one protect against this?

### ISSUE THREAD

**Issue by c3rberus** [dirkjanm/ROADtoken#1]
Just read your blog post on abusing Azure AD SSO in hybrid environments, and while I didn't use ROADToken instead I used RequestAADRefreshToken to get the x-ms-RefreshTokenCredential, I was able to add that cookie and authenticating into https://login.microsoftonline.com/login.srf page.

We have Azure AD P1 for Conditional Access MFA but there was no MFA prompt and it authenticated right into the portal... ouch!

How does one protect against this? Does this only affect hybrid environments where Seamless SSO is turned on, as in if we were Azure AD only we would not be affected?

**Comment by gm0d** [comment]
for anyone else wondering about this, one possibility is to have your "admin" accounts as standard users and enable PIM with approvals. 

as you pointed out, using this method will bypass MFA and any conditional access policy, even MFA in PIM as the claim will be in the cookie already. But the approval will put a hold to it.

**Comment by dirkjanm** [comment]
There's not really a way to prevent this. If an attacker has code execution on your device then by definition they can use the Single Sign On capabilities that the legitimate user of the device has. Best you can do is using additional measures such as PIM to prevent the access of these tokens, and having an EDR that can detect the use of tools like ROADtoken or other malicious activity on the device.
